server:
  port: 8090

spring:
  application:
    name: REPORTE-SERVICE
  profiles:
    active: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    com.dsy1103.msreportes: DEBUG
  file:
    name: logs/ms-reportes.log
  pattern:
    console: "%d{yyyy-MM-dd HH-mm-ss} %-5level [%thread] %logger{36} - %msg%n"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
