spring.application.name=ms-pedidos-test
server.port=0

# H2 en memoria (no necesita MySQL)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA crea las tablas solas
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# Desactivar Flyway en test (H2 no lo necesita)
spring.flyway.enabled=false

# Logs minimos en test
logging.level.root=WARN
logging.level.com.dsy1103.mspedidos=DEBUG