spring.application.name=ms-pedidos
server.port=8084

#Configuración de persistencia (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/prueba3?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Activar el escudo por si la base de datos ya tenía datos previos
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true

#Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true

#Configuración de logs (SLF4J)
logging.level.root=INFO
logging.level.com.dsy1103.mspedidos=DEBUG
logging.file.name=logs/ms-pedidos.log
logging.pattern.console=%d{yyyy-MM-dd HH-mm-ss} %-5level [%thread] %logger{36} - %msg%n